### ISSUE TITLE
How to change owner of root inode

### ISSUE THREAD

**Issue by markh-de** [bestouff/genext2fs#6]
We use genext2fs in a Buildroot (i.e. genimage) environment. We need to change the owner of the root (/) node in order to control the owner of the mountpoint when the created ext2 partition is mounted in the target embedded system.
The ownership of the root directory tree passed via `-d` is ignored.
So I tried with `-D`, but a devtable containing something like
```
/ d 755 1000 1000 - - - - -
```
is unfortunately rejected with
```
genext2fs: bad name '/' (contains a slash)
```
As creation of the ext2 image is part of a (user) build process, we cannot temporarily mount the filesystem to do the required `chmod` at the mountpoint level, as this would require root permissions. All we can use is a fakeroot environment.

Can you please tell us how to change the root node owner, or could you maybe point us in another direction (maybe some idea for post-processing; unfortunately there is no `e2chmod` in `e2tools` - and `e2mkdir` does nothing for existing directories).

Thank you very much!

**Comment by josch** [comment]
Pull request pull/14 addresses this issue. The problem was, that genext2fs unconditionally called dirname and basename on the path. This cause that the basename contained a single slash which is of course forbidden for a filename.

You might also be interested in pull/11 which allows you to pass a tarball to genext2fs. The tarball can contain arbitrary permissions which will be reflected in the generated ext2 image. This means that you don't anymore have to create a device table file.
